runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /i
  static_dir: static/i

- url: /favicon\.ico
  static_files: static/i/favicon.ico
  upload: static/i/favicon\.ico

- url: /tw-light\.ico
  static_files: static/i/tw-light.ico
  upload: static/i/tw-light\.ico

- url: /.*
  script: main.app
